export const RegisterTypes = {
  REGISTER_USER_START: "REGISTER_USER_START",
  REGISTER_IS_POSTING: "REGISTER_IS_POSTING",
  REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
  REGISTER_USER_FAILURE: "REGISTER_USER_FAILURE",
};
