export const LoginTypes = {
    LOGIN_USER_START: "LOGIN_USER_START",
    LOGIN_IS_FETCHING: "LOGIN_IS_FETCHING",
    LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
    LOGIN_USER_FAILURE: "LOGIN_USER_FAILURE",
    LOGIN_POST_TOKEN_TO_DB: "LOGIN_POST_TOKEN_TO_DB",
};
