export const RoomTypes = {
    ROOM_USER_START: "ROOM_USER_START",
    ROOM_NAME_IS_POSTING: "ROOM_NAME_IS_POSTING",
    ROOM_NAME_POSTING_SUCCESS: "ROOM_NAME_POSTING_SUCCESS",
    ROOM_NAME_POSTING_FAILURE: "ROOM_NAME_POSTING_FAILURE",
};
