export const ChannelTypes = {
    ADD_NEW_CHANNEL: "ADD_NEW_CHANNEL",
    GET_CHANNELS_START: "GET_CHANNELS_START",
    IS_FETCHING_CHANNELS: "IS_FETCHING_CHANNELS",
    GET_CHANNELS_SUCCESS: "GET_CHANNELS_SUCCESS",
    GET_CHANNELS_FAILURE: "GET_CHANNELS_FAILURE",
    ADD_MESSAGES_START: "ADD_MESSAGES_START",
};
